spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      authentication-database: admin
      database: product-db
      host: localhost
      port: 27017
      username: admin
      password: admin
server:
  port: 8090
